package bankapp;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Carl
 */
public class LoanMenu extends javax.swing.JDialog {
    private final Customer customer;
    /**
     * Creates new form DepositMenu
     */
    public LoanMenu(java.awt.Frame parent, boolean modal, Customer customer) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.customer = customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoanAmountL = new javax.swing.JLabel();
        LoanAmount = new javax.swing.JTextField();
        LoanTypeL = new javax.swing.JLabel();
        LoanType = new javax.swing.JComboBox<>();
        TimePeriodL = new javax.swing.JLabel();
        TimePeriod = new javax.swing.JComboBox<>();
        TotalInterestL = new javax.swing.JLabel();
        TotalInterest = new javax.swing.JTextField();
        EMIL = new javax.swing.JLabel();
        EMI = new javax.swing.JTextField();
        LoanSubmit = new javax.swing.JButton();
        LoanCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loan Menu");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        LoanAmountL.setForeground(new java.awt.Color(82, 87, 93));
        LoanAmountL.setText("Loan Amount:");
        getContentPane().add(LoanAmountL);

        LoanAmount.setForeground(new java.awt.Color(82, 87, 93));
        LoanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanAmountActionPerformed(evt);
            }
        });
        getContentPane().add(LoanAmount);

        LoanTypeL.setForeground(new java.awt.Color(82, 87, 93));
        LoanTypeL.setText("Loan Type:");
        getContentPane().add(LoanTypeL);

        LoanType.setBackground(new java.awt.Color(253, 219, 58));
        LoanType.setForeground(new java.awt.Color(82, 87, 93));
        LoanType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Education (9%)", "Home (7%)", "Gold (9%)", "Personal (10%)" }));
        LoanType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanTypeActionPerformed(evt);
            }
        });
        getContentPane().add(LoanType);

        TimePeriodL.setForeground(new java.awt.Color(82, 87, 93));
        TimePeriodL.setText("Term Period (years):");
        getContentPane().add(TimePeriodL);

        TimePeriod.setBackground(new java.awt.Color(253, 219, 58));
        TimePeriod.setForeground(new java.awt.Color(82, 87, 93));
        TimePeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "15" }));
        getContentPane().add(TimePeriod);

        TotalInterestL.setForeground(new java.awt.Color(82, 87, 93));
        TotalInterestL.setText("Total Interest:");
        getContentPane().add(TotalInterestL);

        TotalInterest.setForeground(new java.awt.Color(82, 87, 93));
        getContentPane().add(TotalInterest);

        EMIL.setForeground(new java.awt.Color(82, 87, 93));
        EMIL.setText("EMI (per annum):");
        getContentPane().add(EMIL);

        EMI.setForeground(new java.awt.Color(82, 87, 93));
        getContentPane().add(EMI);

        LoanSubmit.setBackground(new java.awt.Color(82, 87, 93));
        LoanSubmit.setForeground(new java.awt.Color(246, 244, 230));
        LoanSubmit.setText("Submit");
        LoanSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(LoanSubmit);

        LoanCancel.setBackground(new java.awt.Color(82, 87, 93));
        LoanCancel.setForeground(new java.awt.Color(246, 244, 230));
        LoanCancel.setText("Cancel");
        LoanCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanCancelActionPerformed(evt);
            }
        });
        getContentPane().add(LoanCancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoanCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_LoanCancelActionPerformed

    private void LoanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoanAmountActionPerformed

    private void LoanTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoanTypeActionPerformed

    private void LoanSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanSubmitActionPerformed

        StringBuilder warnings = new StringBuilder();
        String LType="", TPeriod="", TInterest="";
        double LAmt = 0, roi=0;
        int timep = 0;
        
        Account account = null;
        if (LoanAmount.getText().isEmpty()) {
            warnings.append("Loan Amount must not be empty.\n");
        } else {
            LAmt = Bank.round(Double.parseDouble(LoanAmount.getText()), 2);
        }
        if (warnings.length() > 0) {
            JOptionPane.showMessageDialog(this, warnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
        } else {
            TPeriod=TimePeriod.getSelectedItem().toString();
            timep=Integer.parseInt(TPeriod);
        }
            LType=LoanType.getSelectedItem().toString();
            if (LoanType.getSelectedItem().toString() == "Education (9%)") {
                roi=9.00;
                account=new Loan(LAmt, roi, timep);
            }
            else if(LoanType.getSelectedItem().toString() == "Home (7%)")
            {
                roi=7.00;
                account=new Loan(LAmt, roi, timep);
            }
            else if(LoanType.getSelectedItem().toString() == "Gold (9%)")
            {
                roi=9.00;
                account=new Loan(LAmt, roi, timep);
            } 
            else if(LoanType.getSelectedItem().toString() == "Personal (10%)")
            {
                roi=10.00;
                account=new Loan(LAmt, roi, timep);
            }
        if(!LoanAmount.getText().isEmpty()){
            EMI.setText(String.valueOf(customer.getAccount().Calcroi(LAmt,roi,timep)));
            TotalInterest.setText(String.valueOf(customer.getAccount().checkInterest(LAmt,roi,timep)));
        }
        
    }//GEN-LAST:event_LoanSubmitActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EMI;
    private javax.swing.JLabel EMIL;
    private javax.swing.JTextField LoanAmount;
    private javax.swing.JLabel LoanAmountL;
    private javax.swing.JButton LoanCancel;
    private javax.swing.JButton LoanSubmit;
    private javax.swing.JComboBox<String> LoanType;
    private javax.swing.JLabel LoanTypeL;
    private javax.swing.JComboBox<String> TimePeriod;
    private javax.swing.JLabel TimePeriodL;
    private javax.swing.JTextField TotalInterest;
    private javax.swing.JLabel TotalInterestL;
    // End of variables declaration//GEN-END:variables
}
